language: rust

script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
    - cargo test --verbose
    - cd sprs-ldl; cargo build --verbose; cd ..
    - cd sprs-ldl; cargo test --verbose; cd ..

notifications:
  email:
    - on_success: change
    - on_failure: always

