language: rust

script:
    - rustc --version
    - cargo --version
    - cargo build --verbose --features "lgpl"
    - cargo test --verbose --features "lgpl"

notifications:
  email:
    - on_success: change
    - on_failure: always

