[package]

name = "sprs"
description = "A sparse matrix library"
version = "0.1.0"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]

readme = "README.rst"
license = "MIT"
repository = "https://github.com/vbarrielle/sprs"
keywords = ["sparse", "matrix", "linear", "algebra"]

exclude = [
    "data/*"
]

[dependencies]

num = "*"
