[package]
name = "sprs_suitesparse_ldl"
description = "sprs bindings to the suitesparse ldl solver"
version = "0.1.0"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/vbarrielle/sprs"

[dependencies]

[dependencies.suitesparse_ldl_sys]
path = "../suitesparse_ldl_sys/"
version = "0.1.0"

[dependencies.sprs]
version = "0.6.0"
path = "../.."
